import React, { Component } from 'react';

export default class Dresses extends Component {
  render() {
    return (
      <div>
      <h3>Bride</h3>  
      <h3>Bridemaids</h3>
      <p>COSMIC,CONSERVATIVE,SCENIC,CRYSTAL,OPTIMUM,PREDATORY,PROTECT,GRINDING,CLOTH,
        GENUINE,SHACKLE,BIPLANE,BETRAY,CHARISMA,ADVENTURE,BOOTLEGGER,QUANTUM,BELLYACHE,PUZZLE,DIAMOND,DEMOCRACY,
        HUMID,ANCHOVIES,ALARM,PROVEN,FACADE,ABSURDLY,
        EVERY,ALWAYS,GRADIENT,CHAIN,ETERNAL,ROTTEN,FATHEAD,AVENGING,ROYAL,EAT,METALLIC,GULF,ANCHOVIES,MODEL,BASTER
        ,BANDSAW,VULTURE,BURNING,CHARGEABLE,BRAVE,ANYTHING,BARTER,CHAIR,DYNAMITE,EVALUATE,CARNIVAL,CONCERT,CRABS,CIRCLING,NIGHTMARE,
        ENJOY,BASKET,WEST,FRENCH,CAPTURED,SPARROW,DAYDREAM,DESOLATE,CANDLE,HONEST,ABNORMALITY,ALREADY,MEGACITY,UNSURE,EMERGENCY,SCAR,SINK,LADYBUG,
        DOBERMAN,EQUATION,FLUTTER,DEGENERATE,MINIMAL,EVIDENCE,DIRT,SWEET,EXTRAVAGANT,AVAILABLE,EMOTION,RICH,EASY,CONTRAST,BUMP,DECONTAMINATION,
        CONTAINER,FORBIDDEN,DIVA,NEEDLE,BASIN,CONCRETE,HORSEPOWER,MARBLE,BASTER,RAPID,GIMMICK,PROVEN,CANNIBALISM,BLASTING,MISSHAPEN,BLEED,GURU,FORTY,PESKY,
        ESSENCE,LARGEST,EMPIRE,SNAKE,BLOCKER,GUIDELINE,AFRAID,CHANNEL,GROUNDS,NOBLE,CARNIVOROUS,WAR,PARROT,ARSON,SISSY,FIGUREHEAD,DIZZY,DUMB,FREQUENT,DREAM,TENSE,DEGRADER,VILLAGE,
        AVIATOR,ISLAND,EUNUCH,HEARING,GALACTIC,INDECENT,CRISIS,MONARCHY,ZOMBIE,VIOLENT,PEST,BLASTER,CONQUEST,TANK,CHAOTIC,CLAY,CEREMONIAL,PREDATOR,IVY,INJURY,ACADEMIC,BITE,BRAND,
        HARM,CHALLENGE,AIM,DOLPHINS,BARBER,CLAIRVOYANT,WATER,ACROBAT,BEST,FACTORY,NICE,ROSE,BECAUSE,BURNING,EXTREME,SPIRITS,COLA,ORPHAN,CONDITION,WRECK,HOMICIDE,HONORARY,CAPTIVE,HOLD,ADAPTIVE,
        PERFECTION,ANALYZE,PROPOSAL,DISSOLVE,REPTILE,SMUGGLER,BULL,HOSTILITY,DRUM,BECOME,DISLIKABLE,BIBLE,FINALE,POTENTIAL,COCONUT,BILLIONAIRE,DISCUSSION,ANCESTOR,DROPS,DEPRESSION,DESTROY,BITE,
        WOLVES,SIDEWAYS,SONIC,DIPLOMATIC,GOOD,ABSENTLY,FORTUNATE,JAR,GAME,CLEVER,COTTON,SALTY,AMNESIA,NOISE,PROPHESY,SOLITARY,CORDS,EXCEPTION,CARAVAN,AUDIENCE,PRIMITIVE,SUBWAY,HORN,GOGGLES,CRIMSON,
        BUMP,BEGINNING,EXPRESSIVE,BIN,AUDACITY,MONGREL,FUNCTIONAL,DESIGN,COMA,BURNT,SOCIAL,LIBERATION,CHECKPOINT,CAVITY,CORROSIVE,BEWITCHING,BLANK,HACK,BLAZE,CHUNK,RING,LADYBUG,BASIN,KING,ESTATE,BLAZE,
        POWER,DRAG,SKIN,BELIEVE,FORGIVEN,GEMS,ESTATE,BELL,CRAZY,ANNIHILATE,INITIAL,HOMICIDAL,ABSTRACTLY,JUNKYARD,EPHEMERAL,DOOM,ABSENTLY,GODSENT,DISCHARGE,COASTAL,GALLERY,HANGMAN,PROFOUND,HEALING,FLAMBOYANT,
        ENEMY,ARMY,BLOCK,THREAT,GENETIC,CONTAMINANT,FORT,LION,CATERPILLAR,BLINKS,BAMBOO,BAYONET,POISONOUS,CUDDLY,SABOTAGE,FRECKLED,ELBOW,FULLY,FLOWERS,MUTATION,DEATHTRAP,JADE,HANGMAN,EMPATHIC,AQUAMARINE,SADISTIC,
        PATTERN,UNION,FEAR,EVIDENCE,BEAM,FLIGHT,HATCH,BRIGHT,DUCK,LUMP,WONDER,ACCOMPLICE,GLOBAL,ACOUSTIC,FLOPHOUSE,PROFILE,CHICKEN,FRESH,CIRCUITRY,DIMENSIONAL,WIG,WEPT,LITTLE,GHOULISH,FEDERATION,MOUNTAIN,SEXIEST
        ,CORRELATION,CANNON,POOR,PHOTOGRAPH,HOLDUP,CATHEDRAL,SURGICAL,BOTTOM,SOLITARY,DOUBLE,BILLION,CROWN,PERILOUS,SADISTIC,PROMISE,DROWN,HOLDING,SADISTIC,CALCULATION,CONSUMER,ANNUAL,HEARTS,CARELESS,MIGHTY,MOONBEAM,
        DISC,SETTLER,ATTITUDE,ABANDONED,EVERY,ROTTEN,SMOOTH,PLANT,TIMID,CRUSHER,FUZZY,MINIPILL,BLEAKLY,STIFF,DIAL,BLIMP,SPIKE,BACKBONE,ORANGUTANG,DEMOLITION,CURATOR,RAT,FATALITY,HOOFS,EXHIBITION,VOLUME,SPIRIT,EXCUSE,
        BACHELOR,UNSURE,ENDLESS,DRAMA,MINIMAL,DIRECTION,BULLDOG,ASTOUNDING,UGLY,DOT,MODERN,EBONY,QUICK,BATCH,DOWNHILL,DECEPTION,DIRT,DAREDEVIL,DESIGN,MIGHTIEST,DOPE,RABBIT,ANTELOPES,CELEBRITY,NOISE,FIREARM,CIRCLE,WASP,
        BENEATH,HOPSCOTCH,GUILTY,CARNAL,FLOWER,BEDTIME,DEADLY,ALLIANCE,AQUARIUM,LIVE,ENCRYPTION,NIGHTFALL,CONSTANT,ASSOCIATE,CRYPT,ANGEL,ORTHODOX,DIRECTION,COMMUNICATION,CALENDAR,BIRD,DOGS,BINOCULAR,SHOCK,TRUST,FEROCIOUS,
        DYNAMIC,WARMTH,HORIZON,CHRONOLOGICAL,WAVEFORM,VACANT,EVENT,CHOLERA,FERTILE,INITIAL,NOISE,MOMENTARY,ALWAYS,MASK,INDUSTRIAL,MUTILATION,CONVULSION,ENFORCER,WEALTHY,ELECTRON,HANGAR,PRIVILEGE,FORMULA,VULTURE,COMBAT,
        ENDLESS,HOTHEAD,WILD,AMULET,GUNK,INSURANCE,ARMS,AGENDA,EMPEROR,CODDLE,IMMUNITY,GRILL,GHOUL,NUMBSKULL,AMBIGUOUS,CORDS,CAMEL,DIZZY,COMMUNION,CLOUD,RACKET,DUEL,KIND,COAST,AVENGING,DIFFICULT,SWARM,ADMIRAL,ADMIRAL,
        LEVITATING,NIGHTFALL,TOY,CRITICAL,FIZZ,POOR,GONE,FRUSTRATION,HAND,DESPERATE,VIBRATOR,PINWHEEL,HEADLOCK,DORMANT,ANTIQUE,DIRECT,NECK,JADE,AFTERNOON,DISOBEY,SWARM,DECODE,GIFTED,CALLING,CROCODILE,FALL,SMUT,DROPS,
        PILGRIM,FLOOD,SADISTIC,INSANE,GRASP,GROAN,ABSURDITY,CHEWABLE,DOOMSDAY,FALCON,GASMASK,DESIGN,ACIDIC,ROOT,ANKH,BED,CONCRETE,LEAF,BATTLE,CEREMONIAL,LIME,TERMINUS,ESTATE,FLUID,AGGRESSION,TRAUMA,UGLY,GUZZLING,
        EARTHMEN,DEVOUT,BLEEP,CHOP,PROPOSAL,BONUS,ABILITY,CREATIVE,HORIZON,MUTAGEN,STEALTHY,ADULT,REPUBLIC,LIQUID,OPEN,AFTERNOON,PLAYGROUND,MASSIVE,DECADE,IDENTITY,AMBUSH,DELIGHT,GRAFFITI,SHOTGUN,CELLULAR,ADEQUATE,
        BIRTHMARK,EGG,EUNUCH,LARGEST,ANTEATER,SIDEWAYS,CHARISMATIC,HOOLIGAN,LIME,NIGHTFALL,PREFAB,PROVIDER,NIGHTFALL,PYTHON,GOAT,PATROL,ANNOYING,JUNIOR,DEATH,FORGIVEN,PLANETARY,BLUSH,APE,MODEL,MESSENGER,LONER,
        PIGSTICKER,EIGHT,SICK,SOON,PRESENT,EXTRAVAGANT,FANG,DISPUTED,MODERN,VIOLENCE,FIELD,
        GRAFFITI,HILLS,BODIES,COMMAND,ANTIQUE,TREE,
        BACKGROUND,FATHER,CRUNCH,ANIMALISTIC,BEWITCHING,
        EXTRACT,ZIPPER,MESSIAH,EERIE,LADYBUG,BREAKABLE,BYE,HOMICIDE,POISONOUS,AMPUTATION,BABBLING,WEIRDO,LEGENDARY,MOMENTARY,IMPROPER,INSANITY,PROOF,
        POTENTIAL,HYAENA,BITTERSWEET,ALPHABETIC,DAMN,AGED,GEOMETRY,MONEY,GLIMMER,RISKY,VULTURE,LEFT,RING,GANGLAND,DEMOCRACY,IMPRINT,MINIPILL,BURIAL,MURKY,CATHEDRAL,POSITION,PESSIMIST,CAPTIVITY,CRUISE,PASTE,COFFIN,
        USELESS,GIBBERISH,PARADISE,HEARTLESS,GRINDING,INVADER,RIGHT,GRAVY,UPTOWN,CHILD,GREASY,WESTERN,LIGHTS,FUMBLING,AMBUSH,ARCHIVE,DEFECTION,CONFRONTATIONAL,ADMISSION,INSANITY,ERASER,CHISEL,UGLY,ELECTRIC,ALIENATE,
        DEVOUT,BOARDER,GADGET,WISE,HANDLER,RISKY,COCOON,DEMON,ATTEMPT,HIDEOUS,DOWNFALL,MODERN,HARNESS,SPEED,BASTION,APPLIED,PARCEL,DEFINITIVE,SEVERAL,COMPLETE,DAMAGE,FERTILITY,HARMONIC,FILTH,HERMIT,GOOFBALL,GIBBERISH,BELONGINGS,PROPHET,SKULL,HOMICIDE,FUNDAMENTAL,EVACUATE,ESCALATOR,AUTOPILOT,BEHIND,CHARISMATIC,HARBOR,ISLAMISM,ZEBRA,CRUCIFIER,CRICKET,HOMESICK,FRUSTRATION,CRUST,BALLISTICS,BILLION,DISTANCING,GAME,FREEZING,BODIES,COGNITIVE,BLESS,LUCKY,ELASTIC,ANGRY,MISSING,NICE,CRUNCH,GRANDIOSE,EXCESSIVE,ROOT,AERODYNAMIC,RED,CURVED,FAITH,GLADNESS,AFTERWORLD,NECROTIC,DEDUCTION,WEIRD,GERM,FORTY,DARK,DREAMLESS,EVERYDAY,HONEY,BEWITCHING,BENEFIT,BALLISTICS,GONE,FINALE,FLINCH,HARMONY,ANALYTICAL,ROBOT,RIDDLE,COYOTES,FOOL,HOMETOWN,BOWYER,DISRUPTER,BORDER,SHARP,DEMOCRATIC,BEARSKIN,HOSE,ARMY,ABSOLUTION,MESSIAH,ANGRIEST,TORNADO,BAGS,ORNAMENTAL,PORT,APOCALYPTIC,BARTER,ATTACKER,BLEAKNESS,SLEEP,CARNIVAL,FIEND,BUCKET,DOME,CHILDISH,GENETIC,CANVAS,ENDORSEMENT,GATEWAY,MOAN,FORCE,EMBRACE,KING,LOCUST,CHERRY,BRUTISH,BLACKNESS,JUNIOR,FOOL,KILLJOY,BLISSFULLY,FIND,APOCALYPSE,ROAST,DEVIL,DEMOLISHMENT,ETHICAL,SEXLESS,BLUE,BELOW,FATE,COURAGEOUS,HAWK,CHURCH,FATALITY,ABATTOIR,HORN,PILLBOX,PUSH,BLUISH,COMPANION,WITNESS,DEVOID,MUTATION,ENVELOPE,HEX,MOONBEAM,RUBBER,CITIZEN,ERROR,FOCUS,PROTEST,NICE,CHEERFUL,GROUND,BARNBURNER,CREATIVE,STIFF,COLA,TRUE,FRAUD,BEHEAD,CURATOR,NORMAL,DISCORD,RANCH,DATA,FOOTWORK,HORSEPOWER,AFTERNOON,GUARANTEED,FERTILITY,NOMADIC,FUSE,APARTMENT,EVERLASTING,CHART,ANTIDEMOCRATIC,FEROCIOUS,RIPE,MOTHER,ARSONIST,HUNT,AGONIZING,CHARADE,DOOM,EMBRACE,PURPLE,AIMLESS,DESCRIPTION,GONE,BLACKOUT,BEING,BEAD,CYNICAL,AIRSPACE,GRITTY,ENCRYPT,EASTERN,CLOCK,PRIVILEGED,CONTAMINATION,GULF,COMMITTEE,ALARM,NECTAR,ALARMING,AVOID,KING,PULL,FACE,ARTIST,CORTEX,MOLECULAR,GYMNAST,FORNICATOR,RICH,SALTY,RAVEN,ACUTE,PORK,LION,HEROES,NATURAL,FINITE,GUARD,DEMOLITION,HOT,AWAKENING,HISTORY,DANCER,HONEYDEW,CANNIBALISM,GOLDFISH,GHOST,ABSORBABLE,DOCTOR,LIQUOR,BEAST,ABNORMALLY,CULTISH,GLORY,CUT,GENUINE,DROWSY,BLOSSOM,WEB,BLOW,LAST,VILLAGE,DESTRUCTION,GORILLA,CARNIVAL,GRIEVING,HOMICIDAL,ADMISSION,ENLIGHTEN,ARROGANT,BLINDNESS,RUST,FIBREGLASS,EAGLE,BUCKET,AMAZEMENT,GARDEN,MUTATION,SKULL,FORMULATION,PROFOUND,CONFIDENT,TREED,CARNIVOROUS,GLOW,CONSULTANT,SPIRITS,AGONIZING,SEVERAL,SHOTGUN,OBSERVER,CRIMINAL,DRIP,NOMAD,QUICK,HAZARD,HUNTER,FLAW,INTRUDER,DECAPITATION,ATTITUDE,BROTHER,FEET,BREAKWATER,BATCH,UGLY,CHEF,ERASER,APPOINTMENT,COLLARBONE,BARGE,</p>
      </div>
    );
  }
}
